# Based on https://github.com/redis/hiredis/blob/master/appveyor.yml
# Appveyor configuration file for CI build of hiredis on Windows (under Cygwin)
environment:
    matrix:
#       - CYG_ROOT: C:\cygwin64
#         CYG_SETUP: setup-x86_64.exe
#         CYG_MIRROR: http://cygwin.mirror.constant.com
#         CYG_CACHE: C:\cygwin64\var\cache\setup
#         CYG_BASH: C:\cygwin64\bin\bash
#         CC: gcc
        - CYG_ROOT: C:\cygwin
          CYG_SETUP: setup-x86.exe
          CYG_MIRROR: http://cygwin.mirror.constant.com
          CYG_CACHE: C:\cygwin\var\cache\setup
          CYG_BASH: C:\cygwin\bin\bash
          CC: gcc
          TARGET: distcheck
          UNITTESTS: src/suricata -l /tmp -u

# Cache Cygwin files to speed up build
cache:
    - '%CYG_CACHE%'
clone_depth: 1

# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
init:
    - git config --global core.autocrlf input

# Install needed build dependencies
install:
    - ps: 'Start-FileDownload "http://cygwin.com/$env:CYG_SETUP" -FileName "$env:CYG_SETUP"'
    - '%CYG_SETUP% --quiet-mode --no-shortcuts --only-site --root "%CYG_ROOT%" --site "%CYG_MIRROR%" --local-package-dir "%CYG_CACHE%" --packages automake,bison,gcc-core,libtool,make,gettext-devel,gettext,intltool,pkg-config,clang,llvm,libpcre-devel,file-devel,wget,zlib-devel,libnss-devel,libnspr-devel,libGeoIP-devel,libyaml-devel,luajit-devel,unzip > NUL 2>&1'
    - '%CYG_BASH% -lc "cygcheck -dc cygwin"'
    - '%CYG_BASH% -lc "wget https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip && ls && unzip WpdPack_4_1_2.zip && ls && cp WpdPack/Lib/libpacket.a $CYG_ROOT/lib/ && ls $CYG_ROOT/lib/ && cp WpdPack/Lib/libwpcap.a $CYG_ROOT/lib/ && ls && ls $CYG_ROOT/lib/ && mkdir -p $CYG_ROOT/usr/include/pcap && cp -r WpdPack/Include/* $CYG_ROOT/usr/include/pcap && echo includepcap && ls $CYG_ROOT/usr/include/pcap"'
    - '%CYG_BASH% -lc "echo post-setup1"'
    - '%CYG_BASH% -lc "ls -l $CYG_ROOT/lib/ && ls -l $CYG_ROOT/usr/include|grep pcap && ls -l $CYG_ROOT/usr/include/pcap"'
    - '%CYG_BASH% -lc "echo post-setup2"'
    - '%CYG_BASH% -lc "ls -l /lib/|grep pcap && echo x ls -lR /usr/include|grep pcap && echo y && ls -l /usr/lib/|grep pcap && echo z"'
    - '%CYG_BASH% -lc "echo post-setup3"'

build_script:
    - 'echo building...'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./autogen.sh"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; ./configure --enable-unittests"'
    - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; make LDFLAGS=$LDFLAGS CC=$CC $TARGET CFLAGS=$CFLAGS && $UNITTESTS"'
